### ISSUE TITLE
Sentence split bugs

### ISSUE THREAD

**Issue by fakhirali** [Finity-Alpha/OpenVoiceChat#38]
The sentence split is done on the basis of a full stop. Currently it does not handle periods used in other contexts like:
Dr. Fakhir or Mr. Saleh etc.

**Comment by SaadBazaz** [comment]
@fakhirali - Try this: https://github.com/nipunsadvilkar/pySBD

**Comment by fakhirali** [comment]
@SaadBazaz this literally solves the problem. Will integrate it when I get time. Thanks for sharing!
